stages:
    - builds
    - tests
    - clippy
    - fmt
    
before_script:
    - export PATH="$HOME/.cargo/bin:$PATH"
    
build:stable:
  stage: builds
  tags:
    - redshift-rs-stable
  script:
    - cargo build --all-features
    
tests:coverage:
  stage: tests
  tags:
    - redshift-kcov-rs-stable
  image: registry.duniter.org/docker/rust/kcov:v0.0.4
  script:
    - RUSTFLAGS="-C link-dead-code" cargo test --no-run
    - kcov --exclude-pattern ".cargo" --include-path=$(pwd)/wotb --verify target/cov target/debug/duniter_wotb-*
    - kcov --exclude-pattern ".cargo" --include-path=$(pwd)/crypto --verify target/cov target/debug/duniter_crypto-*
    - cat target/cov/index.json
  allow_failure: true

tests:stable:
  stage: tests
  tags:
    - redshift-rs-stable
  script:
    - cargo test
    
build_and_tests:beta:
  stage: tests
  tags:
    - redshift-rs-beta
  script:
    - rustup update
    - cargo test
  when: manual
  allow_failure: true
    
build_and_tests:nightly:
  stage: tests
  image: rustlang/rust:nightly
  tags:
    - redshift-rs-nightly
  script:
    - cargo test
  when: manual
  allow_failure: true
  
clippy:
  stage: clippy
  image: rustlang/rust:nightly
  tags:
    - redshift-rs-nightly
  before_script:
    - export PATH="$HOME/.cargo/bin:$PATH"
    - cargo install --force clippy --verbose
  script:
    - cargo clippy --all -- -D warnings --verbose
  allow_failure: true  
  
fmt:
  stage: fmt
  image: rustlang/rust:nightly
  tags:
    - redshift-rs-nightly
  before_script:
    - export PATH="$HOME/.cargo/bin:$PATH"
    - cargo install --force rustfmt-nightly
  script:
    - cargo fmt -- --write-mode=diff
  allow_failure: true