[workspace]
members = [
    "bin/durs-server",
    "lib/core/conf",
    "lib/core/core",
    "lib/core/message",
    "lib/core/module",
    "lib/core/network",
    "lib/modules/blockchain",
    # "lib/modules/skeleton-module",
    "lib/modules/tui",
    "lib/modules/ws2p",
    "lib/modules/ws2p-v1-legacy",
    "lib/modules-lib/ws2p/ws2p-messages",
    "lib/tools/crypto",
    "lib/tools/dal",
    "lib/tools/documents",
    "lib/tools/network-documents",
    "lib/tools/wot",
]
