[workspace]
members = [
    "bin/durs-server",
    "lib/core/conf",
    "lib/core/core",
    "lib/core/message",
    "lib/core/module",
    "lib/core/network",
    "lib/modules/blockchain/blockchain",
    "lib/modules/blockchain/blockchain-dal",
    "lib/modules/skeleton",
    "lib/modules/tui",
    "lib/modules/ws2p-v1-legacy",
    "lib/modules/ws2p/ws2p",
    "lib/modules/ws2p/ws2p-messages",
    "lib/tools/crypto",
    "lib/tools/common-tools",
    "lib/tools/documents",
    "lib/tools/json-pest-parser",
    "lib/tools/network-documents",
    "lib/tests-tools/crypto-tests-tools",
    "lib/tests-tools/documents-tests-tools",
    "lib/tests-tools/rust-tests-tools",
    "lib/tools/wot",
]
