[workspace]
members = [
    "bin/durs-server",
    "lib/blockchain",
    "lib/conf",
    "lib/core",
    "lib/crypto",
    "lib/dal",
    "lib/documents",
    "lib/message",
    "lib/module",
    "lib/network",
    "lib/network-documents",
    # "lib/skeleton-module",
    "lib/tui",
    "lib/wot",
    "lib/ws2p",
    "lib/ws2p-messages",
    "lib/ws2p-v1-legacy"
]
