[package]
name = "durs"
version = "0.1.0-a0.1"
authors = ["librelois <elois@duniter.org>","nanocryk <nanocryk@duniter.org>"]
description = "DUniter-RS (durs) is a new implementation of Duniter protocol and software in Rust, a safe, concurrent, practical language"
license = "AGPL-3.0"

[dependencies]
duniter-core = { path = "./core" }
durs-ws2p = { path = "./ws2p" }
durs-ws2p-v1-legacy = { path = "./ws2p-v1-legacy" }
structopt= "0.2.*"

[target.'cfg(unix)'.dependencies]
duniter-tui = { path = "./tui" }

[features]
default = ["ssl"]
ssl = ["durs-ws2p-v1-legacy/ssl"]
# Treat warnings as a build error.
strict = []

[workspace]
members = [
    "blockchain",
    "conf",
    "core",
    "crypto",
    "dal",
    "documents",
    "message",
    "module",
    "network",
    "tui",
    "wotb",
    "ws2p",
    "ws2p-messages",
    "ws2p-v1-legacy"
]
