[package]
name = "durs"
version = "0.1.1-a1"
authors = ["librelois <elois@duniter.org>","nanocryk <nanocryk@duniter.org>","inso <inso@tuta.io>"]
description = "DURS (Dividende Universel RuSt) is a new implementation of Duniter protocol and software in Rust, a safe, concurrent, practical language"
license = "AGPL-3.0"
repository = "https://git.duniter.org/nodes/rust/duniter-rs"
homepage = "https://git.duniter.org/nodes/rust/duniter-rs"
readme = "README.md"
keywords = ["blockchain", "cryptocurrency", "duniter"]
categories = ["command-line-utilities", "network-programming"]
edition = "2018"

[dependencies]
duniter-network = { path = "../../lib/core/network" }
durs-core = { path = "../../lib/core/core" }
durs-module = { path = "../../lib/core/module" }
#durs-skeleton = { path = "../../lib/modules/skeleton" }
durs-ws2p = { path = "../../lib/modules/ws2p/ws2p" }
durs-ws2p-v1-legacy = { path = "../../lib/modules/ws2p-v1-legacy" }
log = "0.4.*"
structopt = "0.2.*"
human-panic = "1.0.*"

[target.'cfg(unix)'.dependencies]
durs-tui = { path = "../../lib/modules/tui" }

[features]
ssl = ["durs-ws2p-v1-legacy/ssl"]

[package.metadata.deb]
maintainer = "librelois <elois@duniter.org>"
depends = "$auto"
section = "misc"
priority = "optional"
assets = [
    ["../../target/release/durs", "usr/bin/", "755"],
    ["../../images/duniter-rs.png", "usr/share/durs/", "644"],
]
features = ["ssl"]

[package.metadata.deb.variants.arm]
assets = [
    ["../../target/armv7-unknown-linux-gnueabihf/release/durs", "usr/bin/", "755"],
    ["../../images/duniter-rs.png", "usr/share/durs/", "644"],
]
features = ["ssl"]