[package]
name = "durs"
version = "0.1.0-a1"
authors = ["librelois <elois@duniter.org>","nanocryk <nanocryk@duniter.org>","inso <inso@tuta.io>"]
description = "DURS (Dividende Universel RuSt) is a new implementation of Duniter protocol and software in Rust, a safe, concurrent, practical language"
license = "AGPL-3.0"
edition = "2018"

[dependencies]
duniter-core = { path = "../../lib/core/core" }
#durs-skeleton = { path = "../../lib/modules/skeleton" }
durs-ws2p = { path = "../../lib/modules/ws2p/ws2p" }
durs-ws2p-v1-legacy = { path = "../../lib/modules/ws2p-v1-legacy" }
structopt= "0.2.*"

[target.'cfg(unix)'.dependencies]
durs-tui = { path = "../../lib/modules/tui" }

[features]
ssl = ["durs-ws2p-v1-legacy/ssl"]

