[package]
name = "durs-wot"
version = "0.8.0-a0.8"
authors = ["nanocryk <nanocryk@duniter.org>", "elois <elois@duniter.org>"]
description = "Makes Web of Trust computations for the Duniter project."
repository = "https://git.duniter.org/nodes/rust/duniter-rs"
readme = "README.md"
keywords = ["duniter", "wot", "wot", "web", "trust"]
license = "AGPL-3.0"

[lib]
path = "lib.rs"

[dependencies]
serde = "1.0.*"
serde_derive = "1.0.*"
bincode = "1.0.*"
byteorder = "1.2.*"
rayon = "1.0.*"

[features]
# Treat warnings as a build error.
strict = []